blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://discord.gg/cXwcpwtxkS
    about: Please ask questions and get help from the community here.
  - name: Documentation
    url: https://github.com/nameIess/ip_config/blob/master/README.md
    about: Read our documentation to find answers to common questions.